Repository google/zx, pull requests merged in 2025-07, with the labels that each got.

#1254 ci: update github actions
  .github/workflows/dev-publish.yml
  .github/workflows/docs.yml
  .github/workflows/osv.yml
  .github/workflows/publish.yml
  .github/workflows/zizmor.yml
Labels: maintenance

#1258 docs: add fetch timeout example
  docs/api.md
Labels: docs

#1257 Introduce weather fetch example
  examples/fetch-weather.mjs
Labels: docs

#1262 fix: check if `ProcessPromise` is settled on kill and abort
  .size-limit.json
  build/core.cjs
  src/core.ts
  test/core.test.js
Labels: bug

#1265 chore: bump version to v8.7.0, minor docs imprs
  docs/process-promise.md
  package-lock.json
  package.json
  test/smoke/win32.test.js
Labels: docs

#1267 fix: update @webpod/ps to v0.1.4 to handle eperm issues
  .size-limit.json
  build/3rd-party-licenses
  build/vendor-core.cjs
  package-lock.json
  package.json
Labels: bug

#1272 chore: bytes shrinking
  .size-limit.json
  build/cli.cjs
  build/cli.js
  build/core.cjs
  build/core.d.ts
  build/globals.d.ts
  build/index.cjs
  src/cli.ts
  src/core.ts
  src/globals.ts
  src/goods.ts
  src/repl.ts
Labels: maintenance

#1277 refactor: align `AbortController` and `EventEmitter` init approach
  .size-limit.json
  build/cli.js
  build/core.cjs
  build/core.d.ts
  package-lock.json
  package.json
  src/core.ts
Labels: refactoring

#1278 refactor: rm redundant internal vars
  .size-limit.json
  build/core.cjs
  build/util.cjs
  src/core.ts
  src/util.ts
  test/util.test.js
Labels: refactoring

#1279 refactor: minor `promisifyStream` tweak up
  .size-limit.json
  build/cli.js
  build/core.cjs
  src/core.ts
Labels: refactoring

#1280 refactor: align internal props names
  .size-limit.json
  build/cli.js
  build/core.cjs
  build/core.d.ts
  src/core.ts
  test/core.test.js
Labels: refactoring

#1283 feat: export `$` as type
  build/cli.js
  build/core.cjs
  build/core.d.ts
  build/log.d.ts
  src/core.ts
  src/log.ts
  test/core.test.js
Labels: feature

#1285 feat: introduce `Fail` class
  .size-limit.json
  build/cli.cjs
  build/cli.js
  build/core.cjs
  build/core.d.ts
  build/core.js
  build/deps.cjs
  build/error.d.ts
  build/index.cjs
  build/index.js
  package.json
  src/cli.ts
  src/core.ts
  src/deps.ts
  src/error.ts
  src/goods.ts
  test/core.test.js
  test/error.test.ts
  test/export.test.js
  test/package.test.js
Labels: feature

#1286 refactor: use single internal args buffer
  .size-limit.json
  build/cli.js
  build/core.cjs
  src/core.ts
  test/core.test.js
Labels: refactoring

#1289 chore: minor code imprs
  .size-limit.json
  build/core.cjs
  build/util.cjs
  src/core.ts
  src/util.ts
Labels: refactoring

#1290 docs: add architecture notes
  docs/.vitepress/config.mts
  docs/api.md
  docs/architecture.md
  docs/contribution.md
Labels: docs

#1292 docs: describe testing flow
  .github/workflows/test.yml
  docs/architecture.md
  package.json
  test/it/build-npm.test.js
Labels: docs

#1299 chore: bump version to v8.8.0
  package-lock.json
  package.json
Labels: maintenance

#1300 feat: enable many to one piping
  .size-limit.json
  build/core.cjs
  build/core.d.ts
  build/index.cjs
  docs/process-promise.md
  src/core.ts
  src/versions.ts
  test/core.test.js
  test/export.test.js
Labels: feature
